---

- name: Deploying app2
  hosts: ec2
  user: ubuntu
 
  tasks:
  - name: Copying docker-compose file
    copy: src=templates/docker-compose.app.yml dest=~/home/ubuntu/

  - name: Running docker-compose.yml
    command: sudo docker-compose -f ~/home/ubuntu/docker-compose.app.yml up -d
      
  - name: Removing docker compose file
    command: sudo rm -f ~/home/ubuntu/docker-compose.app.yml
